---
- hosts: all 
  become: true 
  tasks:
  - name: install docker  
    apt:
      name:
        - docker-py  
      update_cache: yes
  - name: demarrage docker
    service:
      name: docker-py
      state: started 
      enabled: yes

  - name: index copy
    copy: 
      src: docs/
      dest: /docs
  
  - name: création image result
    docker_image:
      path: ./docs/result
      name: /docs/image_result
      tag: result
      push: yes
  
  - name: création image vote
    docker_image:
      path: ./docs/vote
      name: /docs/image_vote
      tag: vote
      push: yes
  - name: création image worker
    docker_image:
      path: ./docs/worker
      name: /docs/image_worker
      tag: worker
      push: yes
  - name: suppression dossier images
    file: 
     state: absent
     path: /docs