---
- hosts: all 
  become: true 
  tasks:
  # - name: Update the apt package index
  #   become: yes
  #   apt:
  #     name: "*"
  #     state: latest
  #     update_cache: yes
  #     force_apt_get: yes

  # - name: Install packages for apt add repository over HTTPS
  #   become: yes
  #   apt:
  #     name: "{{ packagesdep }}"
  #     force_apt_get: yes
  #     state: latest
  #     update_cache: yes
  #   vars:
  #     packagesdep:
  #     - git
  #     - apt-transport-https
  #     - ca-certificates
  #     - wget
  #     - software-properties-common
  #     - gnupg2
  #     - curl

  # - name: Add Apt signing key from official docker repo
  #   apt_key:
  #     url: https://download.docker.com/linux/debian/gpg
  #     state: present
  # - name: add docker official repository for Debian Stretch
  #   apt_repository:
  #     repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
  #     state: present
  # - name: Index new repo into the cache
  #   become: yes
  #   apt:
  #     name: "*"
  #     state: latest
  #     update_cache: yes
  #     force_apt_get: yes

  # - name: actually install docker
  #   apt:
  #     name: "docker-ce"
  #     state: latest
  
  # - name: Run and enable docker
  #   service:
  #    name: docker
  #    state: started
  #    enabled: true


  # - name: create build directory
  #   file:
  #     path: /home/fm/tp2
  #     state: directory
  #     mode: '0755'

  # - name: index copy
  #   copy: 
  #     src: docs/
  #     dest: /home/fm/tp2
  

# build images
  - name: création image result
    docker_image:
      name: image_result
      build:
        path: /home/fm/tp2/result/Dockerfile
        source: build
      state: present
      
  - name: création image vote
    docker_image:
      name: image_vote
      build:
        path: /home/fm/tp2/vote/Dockerfile
        source: build
      state: present

  - name: création image worker
    docker_image:
      name: image_worker
      build:
        path: /home/fm/tp2/worker/Dockerfile
        source: build
      state: present
    


  # - name: suppression dossier images
  #   file: 
  #    state: absent
  #    path: docs